networks:
  e2e-pod:
    driver: bridge

services:
  searchdb-ocp:
    image: docker.io/opensearchproject/opensearch:latest
    container_name: searchdb-ocp
    networks:
       - e2e-pod
    ports:
      - "9200"
    volumes:
      - ./backend/tests/functional/setup/ocp_opensearch.yml:/usr/share/opensearch/config/opensearch.yml:z
      - ./backend/tests/fixtures/search_db_snapshots/snapshot.tar.gz:/var/tmp/snapshot.tar.gz:z
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    entrypoint:
      - /bin/bash
      - -c
      - |
        # unpack the tar before starting Opensearch
        cd /var/tmp
        tar xfz snapshot.tar.gz
        # now exec the upstream entrypoint so ES boots normally
        exec /usr/share/opensearch/opensearch-docker-entrypoint.sh      

  backend:
    build:
      context: ./backend
      dockerfile: backend.containerfile
    image: backend:latest
    container_name: backend
    depends_on:
      - searchdb-ocp
    networks:
      e2e-pod:
        aliases:
          - backend
    volumes:
      - ./backend/tests/ocpperf_test.toml:/opt/backend/ocpperf.toml:Z
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,localhost:3000,http://frontend:3000,frontend:3000

  db-seed:
    build:
      context: ./backend
      dockerfile: tests/functional.containerfile
    image: functional:latest
    container_name: db-seed
    depends_on:
      - backend
    networks:
      - e2e-pod
    entrypoint: ["python3", "-u", "tests/db_seed.py"]
    restart: "no"

  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.containerfile
      args:
        VITE_PERF_DATA_API_BASE_URL: http://backend:8000
    image: frontend:latest
    container_name: frontend
    networks:
      e2e-pod:
        aliases:
          - frontend
    ports:
      - "127.0.0.1:3000:3000"

  e2e-in-network:
    profiles:
      - e2e-in-network
    build:
      context: ./frontend
      dockerfile: e2e_frontend.containerfile
    image: e2e_frontend:latest
    container_name: e2e-in-network
    depends_on:
      db-seed:
        condition: service_completed_successfully
    networks:
      - e2e-pod
    environment:
      - GUI_BASE_URL=http://frontend:3000
    command: ["run", "cypress:run:e2e"]

  e2e-frontend:
    profiles:
      - e2e
    build:
      context: ./frontend
      dockerfile: e2e_frontend.containerfile
    image: e2e_frontend:latest
    container_name: e2e-frontend
    network_mode: host
    entrypoint: ["npx", "cypress", "run", "--e2e", "--headless"]
    depends_on:
      frontend:
        condition: service_started    
      db-seed:
        condition: service_completed_successfully
    command: ["run", "cypress:run:e2e"]
