networks:
  e2e-pod:
    driver: bridge

services:
  searchdb-ocp:
    image: docker.io/opensearchproject/opensearch:latest
    container_name: searchdb-ocp
    networks:
       - e2e-pod
    ports:
      - "9200"
    volumes:
      - ./backend/tests/functional/setup/ocp_opensearch.yml:/usr/share/opensearch/config/opensearch.yml:z
      - ./backend/tests/fixtures/search_db_snapshots/snapshot.tar.gz:/var/tmp/snapshot.tar.gz:z
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    entrypoint:
      - /bin/bash
      - -c
      - |
        # unpack the tar before starting Opensearch
        cd /var/tmp
        tar xfz snapshot.tar.gz
        # now exec the upstream entrypoint so ES boots normally
        exec /usr/share/opensearch/opensearch-docker-entrypoint.sh      

  backend:
    build:
      context: ./backend
      dockerfile: backend.containerfile
    image: backend:latest
    container_name: backend
    depends_on:
      - searchdb-ocp
    networks:
      e2e-pod:
        aliases:
          - backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend/tests/ocpperf_test.toml:/opt/backend/ocpperf.toml:Z
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,localhost:3000,http://frontend:3000,frontend:3000
      # - CORS_ALLOWED_ORIGINS=*

  db-seed:
    build:
      context: ./backend
      dockerfile: tests/functional.containerfile
    image: functional:latest
    container_name: db-seed
    depends_on:
      - backend
    networks:
      - e2e-pod
    entrypoint: ["python3", "-u", "tests/db_seed.py"]
    restart: "no"

  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.containerfile
      # args:
        # VITE_PERF_DATA_API_BASE_URL: http://backend:8000
    image: frontend:latest
    container_name: frontend
    networks:
      e2e-pod:
        aliases:
          - frontend
    ports:
      - "127.0.0.1:3000:3000"
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "--timeout=2", "http://localhost:3000/"]
    #   interval: 5s
    #   retries: 5
    #   start_period: 5s

  e2e-frontend:
    profiles:
      - e2e
    build:
      context: ./frontend
      dockerfile: e2e_frontend.containerfile
    image: e2e_frontend:latest
    container_name: e2e-frontend
    depends_on:
      # frontend:
      #   condition: service_healthy
      db-seed:
        condition: service_completed_successfully
    networks:
      - e2e-pod
    environment:
      - GUI_BASE_URL=http://frontend:3000
    command: ["run", "cypress:run:e2e"]

  debug:
    image: quay.io/centos/centos:stream9
    container_name: debug
    networks:
      - e2e-pod
    environment:
      - GUI_BASE_URL=http://frontend:3000
      - API_BASE_URL=http://backend:8000
    command: ["sleep", "infinity"]

  # e2e-cypress:
  #   profiles:
  #     - headless
  #   build:
  #     context: ./frontend
  #     dockerfile: e2e_frontend.containerfile
  #   image: e2e-cypress:latest
  #   container_name: e2e-cypress
  #   depends_on:
  #     frontend:
  #       condition: service_started
  #     db-seed:
  #       condition: service_completed_successfully
  #   networks:
  #     - e2e-pod
  #   ports:
  #     127.0.0.1:3001:3001
  #   command: ["run", "cypress:open"]    