/*
AI assistance: The Summary UI code was completely generated by Cursor with
Claude 4 Sonnet. The final form is the result of an interactive dialog between
human and AI assistant, with no manual edits.

Assisted-by: Cursor + claude-4-sonnet
*/
import "./index.less";

import { useEffect, useRef, useCallback } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useSearchParams } from "react-router-dom";

import SummaryDateFilter from "./SummaryDateFilter";
import SummaryTable from "./SummaryTable";

function SummaryTab() {
  const dispatch = useDispatch();
  const hasFetchedRef = useRef(false);
  const [searchParams, setSearchParams] = useSearchParams();

  const summaryState = useSelector((state) => state.summary || {});
  const { products, isLoading, startDate, endDate } = summaryState;
  const fromSideMenu = useSelector(
    (state) => state.sidemenu?.fromSideMenu || false,
  );

  // Dynamically import actions to avoid potential circular dependencies
  const fetchSummaryProducts = useCallback(async () => {
    const { fetchSummaryProducts: fetchProducts } = await import(
      "@/actions/summaryActions"
    );
    dispatch(fetchProducts());
  }, [dispatch]);

  const setSummaryDateFilter = useCallback(
    async (startDate, endDate) => {
      const { setSummaryDateFilter: setFilter } = await import(
        "@/actions/summaryActions"
      );
      dispatch(setFilter(startDate, endDate));
    },
    [dispatch],
  );

  const setFromSideMenuFlag = useCallback(
    async (flag) => {
      const { setFromSideMenuFlag: setFlag } = await import(
        "@/actions/sideMenuActions"
      );
      dispatch(setFlag(flag));
    },
    [dispatch],
  );

  // Parse URL parameters on component mount
  useEffect(() => {
    const urlStartDate = searchParams.get("start_date");
    const urlEndDate = searchParams.get("end_date");

    // If URL has date parameters but Redux doesn't, set them in Redux
    if ((urlStartDate || urlEndDate) && (!startDate || !endDate)) {
      setSummaryDateFilter(urlStartDate, urlEndDate);
    }
  }, [searchParams, startDate, endDate, setSummaryDateFilter]);

  useEffect(() => {
    if (!fromSideMenu && products.length === 0 && !hasFetchedRef.current) {
      fetchSummaryProducts();
      hasFetchedRef.current = true;
    }
    if (fromSideMenu) {
      setFromSideMenuFlag(false);
    }
  }, [fromSideMenu, products, fetchSummaryProducts, setFromSideMenuFlag]);

  const handleDateFilterApply = (newStartDate, newEndDate) => {
    // Update Redux state
    setSummaryDateFilter(newStartDate, newEndDate);

    // Update URL parameters
    const newSearchParams = new URLSearchParams(searchParams);
    if (newStartDate) {
      newSearchParams.set("start_date", newStartDate);
    } else {
      newSearchParams.delete("start_date");
    }
    if (newEndDate) {
      newSearchParams.set("end_date", newEndDate);
    } else {
      newSearchParams.delete("end_date");
    }
    setSearchParams(newSearchParams);
  };

  return (
    <div className="summary-table">
      <SummaryDateFilter
        startDate={startDate}
        endDate={endDate}
        onApply={handleDateFilterApply}
      />
      {isLoading ? (
        <div className="loader">Loading summary data...</div>
      ) : (
        products.length > 0 && <SummaryTable />
      )}
    </div>
  );
}

export default SummaryTab;
