{{ if not .Values.elasticsearch.existingSecretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dashboard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dashboard.labels" . | nindent 4 }}
stringData:
  ocpperf.toml: |
    [elasticsearch]

    [ocp-server]
    port = 8000
{{ end }}
