apiVersion: v1
kind: Service
metadata:
  name: {{ include "dashboard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dashboard.labels" . | nindent 4 }}
spec: 
  type: ClusterIP
  ports:
  - name: dashboard
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: api
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    {{- include "dashboard.selectorLabels" . | nindent 4 }}
 