
export const OCP_INITIAL_DATA = {
    initialState: true,
    success: 0,
    failure: 0,
    total: 0,
    others: 0,
    duration:0,
    benchmarks: ["All"],
    versions: ["All"],
    workers: ["All"],
    ciSystems: ["All"],
    networkTypes: ["All"],
    jobTypes: ["All"],
    rehearses: ["All"],
    allIpsec: ["All"],
    allFips: ["All"],
    allEncrypted: ["All"],
    encryptionTypes: ["All"],
    allPublish: ["All"],
    computeArchs: ["All"],
    controlPlaneArchs: ["All"],
    selectedBenchmark: "All",
    selectedVersion: "All",
    selectedPlatform: "All",
    selectedWorkerCount: "All",
    selectedNetworkType: "All",
    selectedCiSystem: "All",
    selectedJobType: "All",
    selectedRehearse: "All",
    selectedIpsec: "All",
    selectedFips: "All",
    selectedEncrypted: "All",
    selectedEncryptionType: "All",
    selectedPublish: "All",
    selectedComputeArch: "All",
    selectedControlPlaneArch: "All",
    waitForUpdate: false,
    platforms: ["All"],
    copyData: [],
    data: [],
    updatedTime: 'Loading',
    error: null,
    startDate: '',
    endDate: '',
    tableData : [{ name: "Benchmark", value: "benchmark" },
                {name:"Release Stream", value: "releaseStream"},
                {name:"Build", value: "build"},
                {name: "Worker Count", value: "workerNodesCount"},
                {name: "Start Date", value: "startDate"},
                {name: "End Date", value: "endDate"},
                {name: "Status", value: "jobStatus"}],
}

export const QUAY_INITIAL_DATA = {
    initialState: true,
    success: 0,
    failure: 0,
    total: 0,
    others: 0,
    duration:0,
    ciSystems: ["All"],
    platforms: ["All"],
    benchmarks: ["All"],
    releaseStreams: ["All"],
    workers: ["All"],
    hitSizes: ["All"],
    concurrencies: ["All"],
    imagePushPulls: ["All"],
    selectedCiSystem: "All",
    selectedPlatform: "All",
    selectedBenchmark: "All",
    selectedReleaseStream: "All",
    selectedWorkerCount: "All",
    selectedHitSize: "All",
    selectedConcurrency: "All",
    selectedImagePushPulls: "All",
    waitForUpdate: false,
    copyData: [],
    data: [],
    updatedTime: 'Loading',
    error: null,
    startDate: '',
    endDate: '',
    tableData : [{ name: "Benchmark", value: "benchmark" },
    {name:"Release Stream", value: "releaseStream"},
    {name:"Platform", value: "platform"},
    {name: "Worker Count", value: "workerNodesCount"},
    {name: "Start Date", value: "startDate"},
    {name: "End Date", value: "endDate"},
    {name: "Status", value: "jobStatus"}],
}

export const TELCO_INITIAL_DATA = {
    initialState: true,
    success: 0,
    failure: 0,
    total: 0,
    others: 0,
    duration:0,
    ciSystems: ["All"],
    benchmarks: ["All"],
    versions: ["All"],
    releaseStreams: ["All"],
    formals: ["All"],
    nodeNames: ["All"],
    cpus: ["All"],
    selectedCiSystem: "All",
    selectedBenchmark: "All",
    selectedVersion: "All",
    selectedReleaseStream: "All",
    selectedFormal: "All",
    selectedCpu: "All",
    selectedNodeName: "All",
    waitForUpdate: false,
    copyData: [],
    data: [],
    updatedTime: 'Loading',
    error: null,
    startDate: '',
    endDate: '',
    tableData : [{ name: "Benchmark", value: "benchmark" },
    {name:"Release Stream", value: "releaseStream"},
    {name:"Build", value: "ocpVersion"},
    {name:"CPU", value: "cpu"},
    {name:"Node Name", value: "nodeName"},
    {name: "Start Date", value: "startDate"},
    {name: "End Date", value: "endDate"},
    {name: "Status", value: "jobStatus"}],
}

export const CPT_INITIAL_DATA = {
    initialState: true,
    success: 0,
    failure: 0,
    total: 0,
    others: 0,
    testNames: ["All"],
    products: ["All"],
    ciSystems: ["All"],
    statuses: ["All"],
    releaseStreams: ["All"],
    selectedCiSystem: "All",
    selectedProduct: "All",
    selectedTestName: "All",
    selectedJobStatus: "All",
    selectedReleaseStream: "All",
    waitForUpdate: false,
    copyData: [],
    data: [],
    updatedTime: 'Loading',
    error: null,
    startDate: '',
    endDate: '',
    tableData : [{name:"Product", value: "product"},
                { name: "CI System", value: "ciSystem" },
                {name: "Test Name", value: "testName"},
                {name: "Version", value: "version"},
                {name: "Release Stream", value: "releaseStream"},
                {name: "Start Date", value: "startDate"},
                {name: "End Date", value: "endDate"},
                {name: "Build URL", value: "buildUrl"},
                {name: "Status", value: "jobStatus"},],
}

export const GRAPH_INITIAL_DATA = {
    uuid_results: {},
    graphError: false,
}

export const QUAY_GRAPH_INITIAL_DATA = {
    uuid_results: {},
    graphError: false,
}

export const TELCO_GRAPH_INITIAL_DATA = {
    uuid_results: {},
    graphError: false,
}
