/*
AI assistance: The Summary UI code was completely generated by Cursor with
Claude 4 Sonnet. The final form is the result of an interactive dialog between
human and AI assistant, with no manual edits.

Assisted-by: Cursor + claude-4-sonnet
*/
import * as TYPES from "@/actions/types";

const initialState = {
  products: [],
  versions: {}, // { productName: { simpleVersion: [detailedVersions...] } }
  benchmarks: {}, // { "product-version": { benchmarkName: { configurations: {...}, readiness: "..." } } }
  summaryData: {}, // { "product-version-benchmark-config-iteration": data }
  isLoading: false,
  startDate: null,
  endDate: null,
};

const summaryReducer = (state = initialState, action) => {
  switch (action.type) {
    case TYPES.SET_SUMMARY_LOADING:
      return {
        ...state,
        isLoading: true,
      };
    case TYPES.SET_SUMMARY_PRODUCTS:
      return {
        ...state,
        products: action.payload,
      };
    case TYPES.SET_SUMMARY_VERSIONS:
      return {
        ...state,
        versions: {
          ...state.versions,
          [action.payload.product]: action.payload.versions,
        },
      };
    case TYPES.SET_SUMMARY_BENCHMARKS:
      const benchmarkKey = `${action.payload.product}-${action.payload.version}`;
      return {
        ...state,
        benchmarks: {
          ...state.benchmarks,
          [benchmarkKey]: action.payload.benchmarks,
        },
      };
    case TYPES.SET_SUMMARY_DATA:
      const dataKey = `${action.payload.product}-${action.payload.version}-${action.payload.benchmark}-${action.payload.config}-${action.payload.iteration}`;
      return {
        ...state,
        summaryData: {
          ...state.summaryData,
          [dataKey]: action.payload.data,
        },
      };
    case TYPES.SET_SUMMARY_DATE_FILTER:
      return {
        ...state,
        startDate: action.payload.startDate,
        endDate: action.payload.endDate,
      };
    case TYPES.CLEAR_SUMMARY_CACHED_DATA:
      return {
        ...state,
        versions: {},
        benchmarks: {},
        summaryData: {},
      };
    case TYPES.SET_SUMMARY_COMPLETED:
      return {
        ...state,
        isLoading: false,
      };
    default:
      return state;
  }
};

export default summaryReducer;
