/* Loading */
export const LOADING = "LOADING";
export const COMPLETED = "COMPLETED";
export const GRAPH_LOADING = "GRAPH_LOADING";
export const GRAPH_COMPLETED = "GRAPH_COMPLETED";
/* Toast */
export const SHOW_TOAST = "SHOW_TOAST";
export const CLEAR_TOAST = "CLEAR_TOAST";

/* Sidemenu */
export const SET_ACTIVE_MENU_ITEM = "SET_ACTIVE_MENU_ITEM";
export const TOGGLE_SIDE_MENU = "TOGGLE_SIDE_MENU";

/* CPT Jobs */
export const SET_CPT_JOBS_DATA = "SET_CPT_JOBS_DATA";
export const SET_CPT_DATE_FILTER = "SET_CPT_DATE_FILTER";
export const SET_CPT_SORT_DIR = "SET_CPT_SORT_DIR";
export const SET_CPT_SORT_INDEX = "SET_CPT_SORT_INDEX";
export const SET_CPT_INIT_JOBS = "SET_CPT_INIT_JOBS";
export const SET_CPT_FILTER_DATA = "SET_CPT_FILTER_DATA";
export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";
export const SET_FILTER_OPTIONS = "SET_FILTER_OPTIONS";
export const SET_FILTERED_DATA = "SET_FILTERED_DATA";
export const SET_APPLIED_FILTERS = "SET_APPLIED_FILTERS";
export const SET_PAGE = "SET_PAGE";
export const SET_PAGE_OPTIONS = "SET_PAGE_OPTIONS";
export const SET_CPT_SUMMARY = "SET_CPT_SUMMARY";
export const SET_SELECTED_FILTERS = "SET_SELECTED_FILTERS";
/* OCP Jobs */
export const SET_OCP_JOBS_DATA = "SET_OCP_JOBS_DATA";
export const SET_OCP_DATE_FILTER = "SET_OCP_DATE_FILTER";
export const SET_OCP_SORT_INDEX = "SET_OCP_SORT_INDEX";
export const SET_OCP_SORT_DIR = "SET_OCP_SORT_DIR";
export const SET_OCP_PAGE = "SET_OCP_PAGE";
export const SET_OCP_PAGE_OPTIONS = "SET_OCP_PAGE_OPTIONS";
export const SET_OCP_INIT_JOBS = "SET_OCP_INIT_JOBS";
export const SET_OCP_SUMMARY = "SET_OCP_SUMMARY";
export const SET_OCP_FILTER_DATA = "SET_OCP_FILTER_DATA";
export const SET_OCP_CATEGORY_FILTER = "SET_OCP_CATEGORY_FILTER";
export const SET_OCP_FILTER_OPTIONS = "SET_OCP_FILTER_OPTIONS";
export const SET_OCP_FILTERED_DATA = "SET_OCP_FILTERED_DATA";
export const SET_OCP_APPLIED_FILTERS = "SET_OCP_APPLIED_FILTERS";
export const SET_OCP_GRAPH_DATA = "SET_OCP_GRAPH_DATA";
export const SET_OCP_COLUMNS = "SET_OCP_COLUMNS";
export const SET_SELECTED_OCP_FILTERS = "SET_SELECTED_OCP_FILTERS";
/* QUAY Jobs*/
export const SET_QUAY_JOBS_DATA = "SET_QUAY_JOBS_DATA";
export const SET_QUAY_DATE_FILTER = "SET_QUAY_DATE_FILTER";
export const SET_QUAY_SORT_INDEX = "SET_QUAY_SORT_INDEX";
export const SET_QUAY_SORT_DIR = "SET_QUAY_SORT_DIR";
export const SET_QUAY_PAGE = "SET_QUAY_PAGE";
export const SET_QUAY_PAGE_OPTIONS = "SET_QUAY_PAGE_OPTIONS";
export const SET_QUAY_INIT_JOBS = "SET_QUAY_INIT_JOBS";
export const SET_QUAY_FILTERED_DATA = "SET_QUAY_FILTERED_DATA";
export const SET_QUAY_CATEGORY_FILTER = "SET_QUAY_CATEGORY_FILTER";
export const SET_QUAY_FILTER_OPTIONS = "SET_QUAY_FILTER_OPTIONS";
export const SET_QUAY_FILTER_DATA = "SET_QUAY_FILTER_DATA";
export const SET_QUAY_APPLIED_FILTERS = "SET_QUAY_APPLIED_FILTERS";
export const SET_QUAY_SELECTED_FILTERS = "SET_QUAY_SELECTED_FILTERS";
export const SET_QUAY_SUMMARY = "SET_QUAY_SUMMARY";
export const SET_QUAY_COLUMNS = "SET_QUAY_COLUMNS";
export const SET_QUAY_GRAPH_DATA = "SET_QUAY_GRAPH_DATA";
/* Telco Jobs */
export const SET_TELCO_JOBS_DATA = "SET_TELCO_JOBS_DATA";
export const SET_TELCO_DATE_FILTER = "SET_TELCO_DATE_FILTER";
export const SET_TELCO_SORT_INDEX = "SET_TELCO_SORT_INDEX";
export const SET_TELCO_SORT_DIR = "SET_TELCO_SORT_DIR";
export const SET_TELCO_PAGE = "SET_TELCO_PAGE";
export const SET_TELCO_PAGE_OPTIONS = "SET_TELCO_PAGE_OPTIONS";
export const SET_TELCO_INIT_JOBS = "SET_TELCO_INIT_JOBS";
export const SET_TELCO_FILTERED_DATA = "SET_TELCO_FILTERED_DATA";
export const SET_TELCO_CATEGORY_FILTER = "SET_TELCO_CATEGORY_FILTER";
export const SET_TELCO_FILTER_OPTIONS = "SET_TELCO_FILTER_OPTIONS";
export const SET_TELCO_FILTER_DATA = "SET_TELCO_FILTER_DATA";
export const SET_TELCO_APPLIED_FILTERS = "SET_TELCO_APPLIED_FILTERS";
export const SET_TELCO_SELECTED_FILTERS = "SET_TELCO_SELECTED_FILTERS";
export const SET_TELCO_SUMMARY = "SET_TELCO_SUMMARY";
export const SET_TELCO_COLUMNS = "SET_TELCO_COLUMNS";
export const SET_TELCO_GRAPH_DATA = "SET_TELCO_GRAPH_DATA";
/* ILAB JOBS */
export const SET_ILAB_JOBS_DATA = "SET_ILAB_JOBS_DATA";
export const SET_ILAB_DATE_FILTER = "SET_ILAB_DATE_FILTER";
export const SET_ILAB_GRAPH_DATA = "SET_ILAB_GRAPH_DATA";
export const SET_ILAB_MULTIGRAPH_DATA = "SET_ILAB_MULTIGRAPH_DATA";
export const SET_ILAB_TOTAL_ITEMS = "SET_ILAB_TOTAL_ITEMS";
export const SET_ILAB_OFFSET = "SET_ILAB_OFFSET";
export const SET_ILAB_PAGE = "SET_ILAB_PAGE";
export const SET_ILAB_PAGE_OPTIONS = "SET_ILAB_PAGE_OPTIONS";
export const SET_ILAB_METRICS = "SET_ILAB_METRICS";
export const SET_ILAB_SELECTED_METRICS = "SET_ILAB_SELECTED_METRICS";
export const SET_ILAB_PERIODS = "SET_ILAB_PERIODS";
export const SET_ILAB_INIT_JOBS = "SET_ILAB_INIT_JOBS";
export const TOGGLE_COMPARISON_SWITCH = "TOGGLE_COMPARISON_SWITCH";
export const SET_EXPANDED_METAROW = "SET_EXPANDED_METAROW";
