name: Build and Push Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch enough commit info to feed version generator
        fetch-depth: 10
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - uses: Gr1N/setup-poetry@v9
    - name: Install dependencies
      run: |
        cd backend
        poetry install

    - name: Build Frontend Image
      id: build-front
      uses: redhat-actions/buildah-build@v2
      with:
        image: frontend
        context: frontend
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./frontend/frontend.containerfile

    - name: Push frontend image to quay.io
      id: push-front-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-front.outputs.image }}
        tags: ${{ steps.build-front.outputs.tags }}
        registry: quay.io/cloud-bulldozer
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Generate version file
      run: |
        cd backend
        poetry run scripts/version.py

    - name: Build Backend Image
      id: build-back
      run: |
        cd backend
        podman build -t backend:${{ github.sha }} -t backend:latest -f backend.containerfile .  
    - name: Push backend image to quay.io
      id: push-back-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: backend
        tags: latest ${{ github.sha }}
        registry: quay.io/cloud-bulldozer
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}
